package com.ec.customer.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCustomNameIsNull() {
            addCriterion("custom_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomNameIsNotNull() {
            addCriterion("custom_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomNameEqualTo(String value) {
            addCriterion("custom_name =", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotEqualTo(String value) {
            addCriterion("custom_name <>", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameGreaterThan(String value) {
            addCriterion("custom_name >", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameGreaterThanOrEqualTo(String value) {
            addCriterion("custom_name >=", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameLessThan(String value) {
            addCriterion("custom_name <", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameLessThanOrEqualTo(String value) {
            addCriterion("custom_name <=", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameLike(String value) {
            addCriterion("custom_name like", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotLike(String value) {
            addCriterion("custom_name not like", value, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameIn(List<String> values) {
            addCriterion("custom_name in", values, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotIn(List<String> values) {
            addCriterion("custom_name not in", values, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameBetween(String value1, String value2) {
            addCriterion("custom_name between", value1, value2, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomNameNotBetween(String value1, String value2) {
            addCriterion("custom_name not between", value1, value2, "customName");
            return (Criteria) this;
        }

        public Criteria andCustomMobileIsNull() {
            addCriterion("custom_mobile is null");
            return (Criteria) this;
        }

        public Criteria andCustomMobileIsNotNull() {
            addCriterion("custom_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andCustomMobileEqualTo(String value) {
            addCriterion("custom_mobile =", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileNotEqualTo(String value) {
            addCriterion("custom_mobile <>", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileGreaterThan(String value) {
            addCriterion("custom_mobile >", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileGreaterThanOrEqualTo(String value) {
            addCriterion("custom_mobile >=", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileLessThan(String value) {
            addCriterion("custom_mobile <", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileLessThanOrEqualTo(String value) {
            addCriterion("custom_mobile <=", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileLike(String value) {
            addCriterion("custom_mobile like", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileNotLike(String value) {
            addCriterion("custom_mobile not like", value, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileIn(List<String> values) {
            addCriterion("custom_mobile in", values, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileNotIn(List<String> values) {
            addCriterion("custom_mobile not in", values, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileBetween(String value1, String value2) {
            addCriterion("custom_mobile between", value1, value2, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomMobileNotBetween(String value1, String value2) {
            addCriterion("custom_mobile not between", value1, value2, "customMobile");
            return (Criteria) this;
        }

        public Criteria andCustomEmailIsNull() {
            addCriterion("custom_email is null");
            return (Criteria) this;
        }

        public Criteria andCustomEmailIsNotNull() {
            addCriterion("custom_email is not null");
            return (Criteria) this;
        }

        public Criteria andCustomEmailEqualTo(String value) {
            addCriterion("custom_email =", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailNotEqualTo(String value) {
            addCriterion("custom_email <>", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailGreaterThan(String value) {
            addCriterion("custom_email >", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailGreaterThanOrEqualTo(String value) {
            addCriterion("custom_email >=", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailLessThan(String value) {
            addCriterion("custom_email <", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailLessThanOrEqualTo(String value) {
            addCriterion("custom_email <=", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailLike(String value) {
            addCriterion("custom_email like", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailNotLike(String value) {
            addCriterion("custom_email not like", value, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailIn(List<String> values) {
            addCriterion("custom_email in", values, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailNotIn(List<String> values) {
            addCriterion("custom_email not in", values, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailBetween(String value1, String value2) {
            addCriterion("custom_email between", value1, value2, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomEmailNotBetween(String value1, String value2) {
            addCriterion("custom_email not between", value1, value2, "customEmail");
            return (Criteria) this;
        }

        public Criteria andCustomWechatIsNull() {
            addCriterion("custom_wechat is null");
            return (Criteria) this;
        }

        public Criteria andCustomWechatIsNotNull() {
            addCriterion("custom_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andCustomWechatEqualTo(String value) {
            addCriterion("custom_wechat =", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatNotEqualTo(String value) {
            addCriterion("custom_wechat <>", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatGreaterThan(String value) {
            addCriterion("custom_wechat >", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatGreaterThanOrEqualTo(String value) {
            addCriterion("custom_wechat >=", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatLessThan(String value) {
            addCriterion("custom_wechat <", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatLessThanOrEqualTo(String value) {
            addCriterion("custom_wechat <=", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatLike(String value) {
            addCriterion("custom_wechat like", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatNotLike(String value) {
            addCriterion("custom_wechat not like", value, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatIn(List<String> values) {
            addCriterion("custom_wechat in", values, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatNotIn(List<String> values) {
            addCriterion("custom_wechat not in", values, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatBetween(String value1, String value2) {
            addCriterion("custom_wechat between", value1, value2, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomWechatNotBetween(String value1, String value2) {
            addCriterion("custom_wechat not between", value1, value2, "customWechat");
            return (Criteria) this;
        }

        public Criteria andCustomQqIsNull() {
            addCriterion("custom_qq is null");
            return (Criteria) this;
        }

        public Criteria andCustomQqIsNotNull() {
            addCriterion("custom_qq is not null");
            return (Criteria) this;
        }

        public Criteria andCustomQqEqualTo(String value) {
            addCriterion("custom_qq =", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqNotEqualTo(String value) {
            addCriterion("custom_qq <>", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqGreaterThan(String value) {
            addCriterion("custom_qq >", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqGreaterThanOrEqualTo(String value) {
            addCriterion("custom_qq >=", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqLessThan(String value) {
            addCriterion("custom_qq <", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqLessThanOrEqualTo(String value) {
            addCriterion("custom_qq <=", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqLike(String value) {
            addCriterion("custom_qq like", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqNotLike(String value) {
            addCriterion("custom_qq not like", value, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqIn(List<String> values) {
            addCriterion("custom_qq in", values, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqNotIn(List<String> values) {
            addCriterion("custom_qq not in", values, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqBetween(String value1, String value2) {
            addCriterion("custom_qq between", value1, value2, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomQqNotBetween(String value1, String value2) {
            addCriterion("custom_qq not between", value1, value2, "customQq");
            return (Criteria) this;
        }

        public Criteria andCustomContentIsNull() {
            addCriterion("custom_content is null");
            return (Criteria) this;
        }

        public Criteria andCustomContentIsNotNull() {
            addCriterion("custom_content is not null");
            return (Criteria) this;
        }

        public Criteria andCustomContentEqualTo(String value) {
            addCriterion("custom_content =", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentNotEqualTo(String value) {
            addCriterion("custom_content <>", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentGreaterThan(String value) {
            addCriterion("custom_content >", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentGreaterThanOrEqualTo(String value) {
            addCriterion("custom_content >=", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentLessThan(String value) {
            addCriterion("custom_content <", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentLessThanOrEqualTo(String value) {
            addCriterion("custom_content <=", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentLike(String value) {
            addCriterion("custom_content like", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentNotLike(String value) {
            addCriterion("custom_content not like", value, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentIn(List<String> values) {
            addCriterion("custom_content in", values, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentNotIn(List<String> values) {
            addCriterion("custom_content not in", values, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentBetween(String value1, String value2) {
            addCriterion("custom_content between", value1, value2, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomContentNotBetween(String value1, String value2) {
            addCriterion("custom_content not between", value1, value2, "customContent");
            return (Criteria) this;
        }

        public Criteria andCustomTypeIsNull() {
            addCriterion("custom_type is null");
            return (Criteria) this;
        }

        public Criteria andCustomTypeIsNotNull() {
            addCriterion("custom_type is not null");
            return (Criteria) this;
        }

        public Criteria andCustomTypeEqualTo(Integer value) {
            addCriterion("custom_type =", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNotEqualTo(Integer value) {
            addCriterion("custom_type <>", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeGreaterThan(Integer value) {
            addCriterion("custom_type >", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("custom_type >=", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeLessThan(Integer value) {
            addCriterion("custom_type <", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeLessThanOrEqualTo(Integer value) {
            addCriterion("custom_type <=", value, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeIn(List<Integer> values) {
            addCriterion("custom_type in", values, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNotIn(List<Integer> values) {
            addCriterion("custom_type not in", values, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeBetween(Integer value1, Integer value2) {
            addCriterion("custom_type between", value1, value2, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("custom_type not between", value1, value2, "customType");
            return (Criteria) this;
        }

        public Criteria andCustomFromIsNull() {
            addCriterion("custom_from is null");
            return (Criteria) this;
        }

        public Criteria andCustomFromIsNotNull() {
            addCriterion("custom_from is not null");
            return (Criteria) this;
        }

        public Criteria andCustomFromEqualTo(String value) {
            addCriterion("custom_from =", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromNotEqualTo(String value) {
            addCriterion("custom_from <>", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromGreaterThan(String value) {
            addCriterion("custom_from >", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromGreaterThanOrEqualTo(String value) {
            addCriterion("custom_from >=", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromLessThan(String value) {
            addCriterion("custom_from <", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromLessThanOrEqualTo(String value) {
            addCriterion("custom_from <=", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromLike(String value) {
            addCriterion("custom_from like", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromNotLike(String value) {
            addCriterion("custom_from not like", value, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromIn(List<String> values) {
            addCriterion("custom_from in", values, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromNotIn(List<String> values) {
            addCriterion("custom_from not in", values, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromBetween(String value1, String value2) {
            addCriterion("custom_from between", value1, value2, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomFromNotBetween(String value1, String value2) {
            addCriterion("custom_from not between", value1, value2, "customFrom");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlIsNull() {
            addCriterion("custom_visit_url is null");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlIsNotNull() {
            addCriterion("custom_visit_url is not null");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlEqualTo(String value) {
            addCriterion("custom_visit_url =", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlNotEqualTo(String value) {
            addCriterion("custom_visit_url <>", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlGreaterThan(String value) {
            addCriterion("custom_visit_url >", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlGreaterThanOrEqualTo(String value) {
            addCriterion("custom_visit_url >=", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlLessThan(String value) {
            addCriterion("custom_visit_url <", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlLessThanOrEqualTo(String value) {
            addCriterion("custom_visit_url <=", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlLike(String value) {
            addCriterion("custom_visit_url like", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlNotLike(String value) {
            addCriterion("custom_visit_url not like", value, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlIn(List<String> values) {
            addCriterion("custom_visit_url in", values, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlNotIn(List<String> values) {
            addCriterion("custom_visit_url not in", values, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlBetween(String value1, String value2) {
            addCriterion("custom_visit_url between", value1, value2, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andCustomVisitUrlNotBetween(String value1, String value2) {
            addCriterion("custom_visit_url not between", value1, value2, "customVisitUrl");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductBranchIsNull() {
            addCriterion("product_branch is null");
            return (Criteria) this;
        }

        public Criteria andProductBranchIsNotNull() {
            addCriterion("product_branch is not null");
            return (Criteria) this;
        }

        public Criteria andProductBranchEqualTo(String value) {
            addCriterion("product_branch =", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotEqualTo(String value) {
            addCriterion("product_branch <>", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchGreaterThan(String value) {
            addCriterion("product_branch >", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchGreaterThanOrEqualTo(String value) {
            addCriterion("product_branch >=", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchLessThan(String value) {
            addCriterion("product_branch <", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchLessThanOrEqualTo(String value) {
            addCriterion("product_branch <=", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchLike(String value) {
            addCriterion("product_branch like", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotLike(String value) {
            addCriterion("product_branch not like", value, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchIn(List<String> values) {
            addCriterion("product_branch in", values, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotIn(List<String> values) {
            addCriterion("product_branch not in", values, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchBetween(String value1, String value2) {
            addCriterion("product_branch between", value1, value2, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductBranchNotBetween(String value1, String value2) {
            addCriterion("product_branch not between", value1, value2, "productBranch");
            return (Criteria) this;
        }

        public Criteria andProductMaterialIsNull() {
            addCriterion("product_material is null");
            return (Criteria) this;
        }

        public Criteria andProductMaterialIsNotNull() {
            addCriterion("product_material is not null");
            return (Criteria) this;
        }

        public Criteria andProductMaterialEqualTo(String value) {
            addCriterion("product_material =", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialNotEqualTo(String value) {
            addCriterion("product_material <>", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialGreaterThan(String value) {
            addCriterion("product_material >", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("product_material >=", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialLessThan(String value) {
            addCriterion("product_material <", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialLessThanOrEqualTo(String value) {
            addCriterion("product_material <=", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialLike(String value) {
            addCriterion("product_material like", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialNotLike(String value) {
            addCriterion("product_material not like", value, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialIn(List<String> values) {
            addCriterion("product_material in", values, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialNotIn(List<String> values) {
            addCriterion("product_material not in", values, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialBetween(String value1, String value2) {
            addCriterion("product_material between", value1, value2, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductMaterialNotBetween(String value1, String value2) {
            addCriterion("product_material not between", value1, value2, "productMaterial");
            return (Criteria) this;
        }

        public Criteria andProductPricesIsNull() {
            addCriterion("product_prices is null");
            return (Criteria) this;
        }

        public Criteria andProductPricesIsNotNull() {
            addCriterion("product_prices is not null");
            return (Criteria) this;
        }

        public Criteria andProductPricesEqualTo(BigDecimal value) {
            addCriterion("product_prices =", value, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesNotEqualTo(BigDecimal value) {
            addCriterion("product_prices <>", value, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesGreaterThan(BigDecimal value) {
            addCriterion("product_prices >", value, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_prices >=", value, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesLessThan(BigDecimal value) {
            addCriterion("product_prices <", value, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_prices <=", value, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesIn(List<BigDecimal> values) {
            addCriterion("product_prices in", values, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesNotIn(List<BigDecimal> values) {
            addCriterion("product_prices not in", values, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_prices between", value1, value2, "productPrices");
            return (Criteria) this;
        }

        public Criteria andProductPricesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_prices not between", value1, value2, "productPrices");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceIsNull() {
            addCriterion("deliver_province is null");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceIsNotNull() {
            addCriterion("deliver_province is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceEqualTo(String value) {
            addCriterion("deliver_province =", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceNotEqualTo(String value) {
            addCriterion("deliver_province <>", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceGreaterThan(String value) {
            addCriterion("deliver_province >", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_province >=", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceLessThan(String value) {
            addCriterion("deliver_province <", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceLessThanOrEqualTo(String value) {
            addCriterion("deliver_province <=", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceLike(String value) {
            addCriterion("deliver_province like", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceNotLike(String value) {
            addCriterion("deliver_province not like", value, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceIn(List<String> values) {
            addCriterion("deliver_province in", values, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceNotIn(List<String> values) {
            addCriterion("deliver_province not in", values, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceBetween(String value1, String value2) {
            addCriterion("deliver_province between", value1, value2, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverProvinceNotBetween(String value1, String value2) {
            addCriterion("deliver_province not between", value1, value2, "deliverProvince");
            return (Criteria) this;
        }

        public Criteria andDeliverCityIsNull() {
            addCriterion("deliver_city is null");
            return (Criteria) this;
        }

        public Criteria andDeliverCityIsNotNull() {
            addCriterion("deliver_city is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverCityEqualTo(String value) {
            addCriterion("deliver_city =", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityNotEqualTo(String value) {
            addCriterion("deliver_city <>", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityGreaterThan(String value) {
            addCriterion("deliver_city >", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_city >=", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityLessThan(String value) {
            addCriterion("deliver_city <", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityLessThanOrEqualTo(String value) {
            addCriterion("deliver_city <=", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityLike(String value) {
            addCriterion("deliver_city like", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityNotLike(String value) {
            addCriterion("deliver_city not like", value, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityIn(List<String> values) {
            addCriterion("deliver_city in", values, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityNotIn(List<String> values) {
            addCriterion("deliver_city not in", values, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityBetween(String value1, String value2) {
            addCriterion("deliver_city between", value1, value2, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCityNotBetween(String value1, String value2) {
            addCriterion("deliver_city not between", value1, value2, "deliverCity");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyIsNull() {
            addCriterion("deliver_county is null");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyIsNotNull() {
            addCriterion("deliver_county is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyEqualTo(String value) {
            addCriterion("deliver_county =", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyNotEqualTo(String value) {
            addCriterion("deliver_county <>", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyGreaterThan(String value) {
            addCriterion("deliver_county >", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_county >=", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyLessThan(String value) {
            addCriterion("deliver_county <", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyLessThanOrEqualTo(String value) {
            addCriterion("deliver_county <=", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyLike(String value) {
            addCriterion("deliver_county like", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyNotLike(String value) {
            addCriterion("deliver_county not like", value, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyIn(List<String> values) {
            addCriterion("deliver_county in", values, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyNotIn(List<String> values) {
            addCriterion("deliver_county not in", values, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyBetween(String value1, String value2) {
            addCriterion("deliver_county between", value1, value2, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverCountyNotBetween(String value1, String value2) {
            addCriterion("deliver_county not between", value1, value2, "deliverCounty");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssIsNull() {
            addCriterion("deliver_adderss is null");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssIsNotNull() {
            addCriterion("deliver_adderss is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssEqualTo(String value) {
            addCriterion("deliver_adderss =", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssNotEqualTo(String value) {
            addCriterion("deliver_adderss <>", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssGreaterThan(String value) {
            addCriterion("deliver_adderss >", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_adderss >=", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssLessThan(String value) {
            addCriterion("deliver_adderss <", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssLessThanOrEqualTo(String value) {
            addCriterion("deliver_adderss <=", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssLike(String value) {
            addCriterion("deliver_adderss like", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssNotLike(String value) {
            addCriterion("deliver_adderss not like", value, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssIn(List<String> values) {
            addCriterion("deliver_adderss in", values, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssNotIn(List<String> values) {
            addCriterion("deliver_adderss not in", values, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssBetween(String value1, String value2) {
            addCriterion("deliver_adderss between", value1, value2, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverAdderssNotBetween(String value1, String value2) {
            addCriterion("deliver_adderss not between", value1, value2, "deliverAdderss");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIsNull() {
            addCriterion("deliver_time is null");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIsNotNull() {
            addCriterion("deliver_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeEqualTo(String value) {
            addCriterion("deliver_time =", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotEqualTo(String value) {
            addCriterion("deliver_time <>", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeGreaterThan(String value) {
            addCriterion("deliver_time >", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_time >=", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLessThan(String value) {
            addCriterion("deliver_time <", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLessThanOrEqualTo(String value) {
            addCriterion("deliver_time <=", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLike(String value) {
            addCriterion("deliver_time like", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotLike(String value) {
            addCriterion("deliver_time not like", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIn(List<String> values) {
            addCriterion("deliver_time in", values, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotIn(List<String> values) {
            addCriterion("deliver_time not in", values, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeBetween(String value1, String value2) {
            addCriterion("deliver_time between", value1, value2, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotBetween(String value1, String value2) {
            addCriterion("deliver_time not between", value1, value2, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusIsNull() {
            addCriterion("deliver_status is null");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusIsNotNull() {
            addCriterion("deliver_status is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusEqualTo(Integer value) {
            addCriterion("deliver_status =", value, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusNotEqualTo(Integer value) {
            addCriterion("deliver_status <>", value, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusGreaterThan(Integer value) {
            addCriterion("deliver_status >", value, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deliver_status >=", value, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusLessThan(Integer value) {
            addCriterion("deliver_status <", value, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusLessThanOrEqualTo(Integer value) {
            addCriterion("deliver_status <=", value, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusIn(List<Integer> values) {
            addCriterion("deliver_status in", values, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusNotIn(List<Integer> values) {
            addCriterion("deliver_status not in", values, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusBetween(Integer value1, Integer value2) {
            addCriterion("deliver_status between", value1, value2, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deliver_status not between", value1, value2, "deliverStatus");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIsNull() {
            addCriterion("deliver_express is null");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIsNotNull() {
            addCriterion("deliver_express is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressEqualTo(String value) {
            addCriterion("deliver_express =", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressNotEqualTo(String value) {
            addCriterion("deliver_express <>", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressGreaterThan(String value) {
            addCriterion("deliver_express >", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_express >=", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressLessThan(String value) {
            addCriterion("deliver_express <", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressLessThanOrEqualTo(String value) {
            addCriterion("deliver_express <=", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressLike(String value) {
            addCriterion("deliver_express like", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressNotLike(String value) {
            addCriterion("deliver_express not like", value, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIn(List<String> values) {
            addCriterion("deliver_express in", values, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressNotIn(List<String> values) {
            addCriterion("deliver_express not in", values, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressBetween(String value1, String value2) {
            addCriterion("deliver_express between", value1, value2, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressNotBetween(String value1, String value2) {
            addCriterion("deliver_express not between", value1, value2, "deliverExpress");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdIsNull() {
            addCriterion("deliver_express_id is null");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdIsNotNull() {
            addCriterion("deliver_express_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdEqualTo(String value) {
            addCriterion("deliver_express_id =", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdNotEqualTo(String value) {
            addCriterion("deliver_express_id <>", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdGreaterThan(String value) {
            addCriterion("deliver_express_id >", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdGreaterThanOrEqualTo(String value) {
            addCriterion("deliver_express_id >=", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdLessThan(String value) {
            addCriterion("deliver_express_id <", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdLessThanOrEqualTo(String value) {
            addCriterion("deliver_express_id <=", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdLike(String value) {
            addCriterion("deliver_express_id like", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdNotLike(String value) {
            addCriterion("deliver_express_id not like", value, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdIn(List<String> values) {
            addCriterion("deliver_express_id in", values, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdNotIn(List<String> values) {
            addCriterion("deliver_express_id not in", values, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdBetween(String value1, String value2) {
            addCriterion("deliver_express_id between", value1, value2, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andDeliverExpressIdNotBetween(String value1, String value2) {
            addCriterion("deliver_express_id not between", value1, value2, "deliverExpressId");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createby is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createby is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Long value) {
            addCriterion("createby =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Long value) {
            addCriterion("createby <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Long value) {
            addCriterion("createby >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Long value) {
            addCriterion("createby >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Long value) {
            addCriterion("createby <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Long value) {
            addCriterion("createby <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Long> values) {
            addCriterion("createby in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Long> values) {
            addCriterion("createby not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Long value1, Long value2) {
            addCriterion("createby between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Long value1, Long value2) {
            addCriterion("createby not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreateipIsNull() {
            addCriterion("createip is null");
            return (Criteria) this;
        }

        public Criteria andCreateipIsNotNull() {
            addCriterion("createip is not null");
            return (Criteria) this;
        }

        public Criteria andCreateipEqualTo(String value) {
            addCriterion("createip =", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipNotEqualTo(String value) {
            addCriterion("createip <>", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipGreaterThan(String value) {
            addCriterion("createip >", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipGreaterThanOrEqualTo(String value) {
            addCriterion("createip >=", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipLessThan(String value) {
            addCriterion("createip <", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipLessThanOrEqualTo(String value) {
            addCriterion("createip <=", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipLike(String value) {
            addCriterion("createip like", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipNotLike(String value) {
            addCriterion("createip not like", value, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipIn(List<String> values) {
            addCriterion("createip in", values, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipNotIn(List<String> values) {
            addCriterion("createip not in", values, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipBetween(String value1, String value2) {
            addCriterion("createip between", value1, value2, "createip");
            return (Criteria) this;
        }

        public Criteria andCreateipNotBetween(String value1, String value2) {
            addCriterion("createip not between", value1, value2, "createip");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("updateby is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("updateby is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Long value) {
            addCriterion("updateby =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Long value) {
            addCriterion("updateby <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Long value) {
            addCriterion("updateby >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Long value) {
            addCriterion("updateby >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Long value) {
            addCriterion("updateby <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Long value) {
            addCriterion("updateby <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Long> values) {
            addCriterion("updateby in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Long> values) {
            addCriterion("updateby not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Long value1, Long value2) {
            addCriterion("updateby between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Long value1, Long value2) {
            addCriterion("updateby not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateipIsNull() {
            addCriterion("updateip is null");
            return (Criteria) this;
        }

        public Criteria andUpdateipIsNotNull() {
            addCriterion("updateip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateipEqualTo(String value) {
            addCriterion("updateip =", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipNotEqualTo(String value) {
            addCriterion("updateip <>", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipGreaterThan(String value) {
            addCriterion("updateip >", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipGreaterThanOrEqualTo(String value) {
            addCriterion("updateip >=", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipLessThan(String value) {
            addCriterion("updateip <", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipLessThanOrEqualTo(String value) {
            addCriterion("updateip <=", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipLike(String value) {
            addCriterion("updateip like", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipNotLike(String value) {
            addCriterion("updateip not like", value, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipIn(List<String> values) {
            addCriterion("updateip in", values, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipNotIn(List<String> values) {
            addCriterion("updateip not in", values, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipBetween(String value1, String value2) {
            addCriterion("updateip between", value1, value2, "updateip");
            return (Criteria) this;
        }

        public Criteria andUpdateipNotBetween(String value1, String value2) {
            addCriterion("updateip not between", value1, value2, "updateip");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeIsNull() {
            addCriterion("browser_type is null");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeIsNotNull() {
            addCriterion("browser_type is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeEqualTo(String value) {
            addCriterion("browser_type =", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeNotEqualTo(String value) {
            addCriterion("browser_type <>", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeGreaterThan(String value) {
            addCriterion("browser_type >", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("browser_type >=", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeLessThan(String value) {
            addCriterion("browser_type <", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeLessThanOrEqualTo(String value) {
            addCriterion("browser_type <=", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeLike(String value) {
            addCriterion("browser_type like", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeNotLike(String value) {
            addCriterion("browser_type not like", value, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeIn(List<String> values) {
            addCriterion("browser_type in", values, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeNotIn(List<String> values) {
            addCriterion("browser_type not in", values, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeBetween(String value1, String value2) {
            addCriterion("browser_type between", value1, value2, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserTypeNotBetween(String value1, String value2) {
            addCriterion("browser_type not between", value1, value2, "browserType");
            return (Criteria) this;
        }

        public Criteria andBrowserNameIsNull() {
            addCriterion("browser_name is null");
            return (Criteria) this;
        }

        public Criteria andBrowserNameIsNotNull() {
            addCriterion("browser_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserNameEqualTo(String value) {
            addCriterion("browser_name =", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotEqualTo(String value) {
            addCriterion("browser_name <>", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameGreaterThan(String value) {
            addCriterion("browser_name >", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameGreaterThanOrEqualTo(String value) {
            addCriterion("browser_name >=", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameLessThan(String value) {
            addCriterion("browser_name <", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameLessThanOrEqualTo(String value) {
            addCriterion("browser_name <=", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameLike(String value) {
            addCriterion("browser_name like", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotLike(String value) {
            addCriterion("browser_name not like", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameIn(List<String> values) {
            addCriterion("browser_name in", values, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotIn(List<String> values) {
            addCriterion("browser_name not in", values, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameBetween(String value1, String value2) {
            addCriterion("browser_name between", value1, value2, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotBetween(String value1, String value2) {
            addCriterion("browser_name not between", value1, value2, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserOsIsNull() {
            addCriterion("browser_os is null");
            return (Criteria) this;
        }

        public Criteria andBrowserOsIsNotNull() {
            addCriterion("browser_os is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserOsEqualTo(String value) {
            addCriterion("browser_os =", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsNotEqualTo(String value) {
            addCriterion("browser_os <>", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsGreaterThan(String value) {
            addCriterion("browser_os >", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsGreaterThanOrEqualTo(String value) {
            addCriterion("browser_os >=", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsLessThan(String value) {
            addCriterion("browser_os <", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsLessThanOrEqualTo(String value) {
            addCriterion("browser_os <=", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsLike(String value) {
            addCriterion("browser_os like", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsNotLike(String value) {
            addCriterion("browser_os not like", value, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsIn(List<String> values) {
            addCriterion("browser_os in", values, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsNotIn(List<String> values) {
            addCriterion("browser_os not in", values, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsBetween(String value1, String value2) {
            addCriterion("browser_os between", value1, value2, "browserOs");
            return (Criteria) this;
        }

        public Criteria andBrowserOsNotBetween(String value1, String value2) {
            addCriterion("browser_os not between", value1, value2, "browserOs");
            return (Criteria) this;
        }

        public Criteria andRateUnitIsNull() {
            addCriterion("rate_unit is null");
            return (Criteria) this;
        }

        public Criteria andRateUnitIsNotNull() {
            addCriterion("rate_unit is not null");
            return (Criteria) this;
        }

        public Criteria andRateUnitEqualTo(String value) {
            addCriterion("rate_unit =", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitNotEqualTo(String value) {
            addCriterion("rate_unit <>", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitGreaterThan(String value) {
            addCriterion("rate_unit >", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitGreaterThanOrEqualTo(String value) {
            addCriterion("rate_unit >=", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitLessThan(String value) {
            addCriterion("rate_unit <", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitLessThanOrEqualTo(String value) {
            addCriterion("rate_unit <=", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitLike(String value) {
            addCriterion("rate_unit like", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitNotLike(String value) {
            addCriterion("rate_unit not like", value, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitIn(List<String> values) {
            addCriterion("rate_unit in", values, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitNotIn(List<String> values) {
            addCriterion("rate_unit not in", values, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitBetween(String value1, String value2) {
            addCriterion("rate_unit between", value1, value2, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateUnitNotBetween(String value1, String value2) {
            addCriterion("rate_unit not between", value1, value2, "rateUnit");
            return (Criteria) this;
        }

        public Criteria andRateValIsNull() {
            addCriterion("rate_val is null");
            return (Criteria) this;
        }

        public Criteria andRateValIsNotNull() {
            addCriterion("rate_val is not null");
            return (Criteria) this;
        }

        public Criteria andRateValEqualTo(Integer value) {
            addCriterion("rate_val =", value, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValNotEqualTo(Integer value) {
            addCriterion("rate_val <>", value, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValGreaterThan(Integer value) {
            addCriterion("rate_val >", value, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValGreaterThanOrEqualTo(Integer value) {
            addCriterion("rate_val >=", value, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValLessThan(Integer value) {
            addCriterion("rate_val <", value, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValLessThanOrEqualTo(Integer value) {
            addCriterion("rate_val <=", value, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValIn(List<Integer> values) {
            addCriterion("rate_val in", values, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValNotIn(List<Integer> values) {
            addCriterion("rate_val not in", values, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValBetween(Integer value1, Integer value2) {
            addCriterion("rate_val between", value1, value2, "rateVal");
            return (Criteria) this;
        }

        public Criteria andRateValNotBetween(Integer value1, Integer value2) {
            addCriterion("rate_val not between", value1, value2, "rateVal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}