package com.ec.customer.model;

import java.util.Date;

public class Visitors {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.custom_type
     *
     * @mbg.generated
     */
    private Integer customType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.custom_from
     *
     * @mbg.generated
     */
    private String customFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.custom_visit_url
     *
     * @mbg.generated
     */
    private String customVisitUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.createdate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.createip
     *
     * @mbg.generated
     */
    private String createip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.browser_name
     *
     * @mbg.generated
     */
    private String browserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.browser_os
     *
     * @mbg.generated
     */
    private String browserOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.rate_unit
     *
     * @mbg.generated
     */
    private String rateUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.rate_val
     *
     * @mbg.generated
     */
    private Integer rateVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.custom_type
     *
     * @return the value of visitors.custom_type
     *
     * @mbg.generated
     */
    public Integer getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.custom_type
     *
     * @param customType the value for visitors.custom_type
     *
     * @mbg.generated
     */
    public void setCustomType(Integer customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.custom_from
     *
     * @return the value of visitors.custom_from
     *
     * @mbg.generated
     */
    public String getCustomFrom() {
        return customFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.custom_from
     *
     * @param customFrom the value for visitors.custom_from
     *
     * @mbg.generated
     */
    public void setCustomFrom(String customFrom) {
        this.customFrom = customFrom == null ? null : customFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.custom_visit_url
     *
     * @return the value of visitors.custom_visit_url
     *
     * @mbg.generated
     */
    public String getCustomVisitUrl() {
        return customVisitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.custom_visit_url
     *
     * @param customVisitUrl the value for visitors.custom_visit_url
     *
     * @mbg.generated
     */
    public void setCustomVisitUrl(String customVisitUrl) {
        this.customVisitUrl = customVisitUrl == null ? null : customVisitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.product_type
     *
     * @return the value of visitors.product_type
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.product_type
     *
     * @param productType the value for visitors.product_type
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.createdate
     *
     * @return the value of visitors.createdate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.createdate
     *
     * @param createdate the value for visitors.createdate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.createip
     *
     * @return the value of visitors.createip
     *
     * @mbg.generated
     */
    public String getCreateip() {
        return createip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.createip
     *
     * @param createip the value for visitors.createip
     *
     * @mbg.generated
     */
    public void setCreateip(String createip) {
        this.createip = createip == null ? null : createip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.browser_name
     *
     * @return the value of visitors.browser_name
     *
     * @mbg.generated
     */
    public String getBrowserName() {
        return browserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.browser_name
     *
     * @param browserName the value for visitors.browser_name
     *
     * @mbg.generated
     */
    public void setBrowserName(String browserName) {
        this.browserName = browserName == null ? null : browserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.browser_os
     *
     * @return the value of visitors.browser_os
     *
     * @mbg.generated
     */
    public String getBrowserOs() {
        return browserOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.browser_os
     *
     * @param browserOs the value for visitors.browser_os
     *
     * @mbg.generated
     */
    public void setBrowserOs(String browserOs) {
        this.browserOs = browserOs == null ? null : browserOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.status
     *
     * @return the value of visitors.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.status
     *
     * @param status the value for visitors.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.rate_unit
     *
     * @return the value of visitors.rate_unit
     *
     * @mbg.generated
     */
    public String getRateUnit() {
        return rateUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.rate_unit
     *
     * @param rateUnit the value for visitors.rate_unit
     *
     * @mbg.generated
     */
    public void setRateUnit(String rateUnit) {
        this.rateUnit = rateUnit == null ? null : rateUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.rate_val
     *
     * @return the value of visitors.rate_val
     *
     * @mbg.generated
     */
    public Integer getRateVal() {
        return rateVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.rate_val
     *
     * @param rateVal the value for visitors.rate_val
     *
     * @mbg.generated
     */
    public void setRateVal(Integer rateVal) {
        this.rateVal = rateVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Visitors other = (Visitors) that;
        return (this.getCustomType() == null ? other.getCustomType() == null : this.getCustomType().equals(other.getCustomType()))
            && (this.getCustomFrom() == null ? other.getCustomFrom() == null : this.getCustomFrom().equals(other.getCustomFrom()))
            && (this.getCustomVisitUrl() == null ? other.getCustomVisitUrl() == null : this.getCustomVisitUrl().equals(other.getCustomVisitUrl()))
            && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreateip() == null ? other.getCreateip() == null : this.getCreateip().equals(other.getCreateip()))
            && (this.getBrowserName() == null ? other.getBrowserName() == null : this.getBrowserName().equals(other.getBrowserName()))
            && (this.getBrowserOs() == null ? other.getBrowserOs() == null : this.getBrowserOs().equals(other.getBrowserOs()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRateUnit() == null ? other.getRateUnit() == null : this.getRateUnit().equals(other.getRateUnit()))
            && (this.getRateVal() == null ? other.getRateVal() == null : this.getRateVal().equals(other.getRateVal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustomType() == null) ? 0 : getCustomType().hashCode());
        result = prime * result + ((getCustomFrom() == null) ? 0 : getCustomFrom().hashCode());
        result = prime * result + ((getCustomVisitUrl() == null) ? 0 : getCustomVisitUrl().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreateip() == null) ? 0 : getCreateip().hashCode());
        result = prime * result + ((getBrowserName() == null) ? 0 : getBrowserName().hashCode());
        result = prime * result + ((getBrowserOs() == null) ? 0 : getBrowserOs().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRateUnit() == null) ? 0 : getRateUnit().hashCode());
        result = prime * result + ((getRateVal() == null) ? 0 : getRateVal().hashCode());
        return result;
    }
}