package com.ec.customer.dao;

import com.ec.customer.model.Orders;
import com.ec.customer.model.Visitors;
import com.ec.customer.model.VisitorsExample;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    long countByExample(VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    int deleteByExample(VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    int insert(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    int insertSelective(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    List<Visitors> selectByExample(VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Visitors record, @Param("example") VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Visitors record, @Param("example") VisitorsExample example);
    
    
    int createTable();
    int insertByList(Collection<Visitors> records);
    
}